version: '2'

services:
  substrate:
    container_name: substrate
    image: cerebellumnetwork/pos-node:v5.1.2
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    command: bash -c "/usr/local/bin/cere --dev --rpc-port 9944 --unsafe-rpc-external --rpc-cors all --rpc-methods unsafe --offchain-worker always"

  gsrpc-test:
    image: gsrpc-test
    build: .
    environment:
      - RPC_URL=ws://substrate:9944
      - TEST_PRIV_KEY=//Alice
    volumes:
      - "$PWD:/go-substrate-rpc-client"
